tomprogrammer/rust-ascii

src/lib.rs
new orphan check does not play well with Hash. Disabled temporarily as per https://github.com/nikomatsakis/rust/commit/c61a0092bc236c4be4cb691fcd50ff50e91ab0d6.
Also, Sized? is now the default, and OwnedAsciiCast needs to explicitly inherit from Sized
=> rustup 2015-01-02

src/lib.rs
The ascii crate now provides types for owned ascii strings and borrowed
ascii slices. Their implementation should allow them to be used like
`String` and `str`.
Changes:
- `AsciiString` replaces `Vec<Ascii>`
- `AsciiStr` replaces `[Ascii]`
- ~~Remove `Ascii::to_lowercase()` and `Ascii::to_uppercase()`~~
- Remove traits `IntoString`, `IntoBytes` and `AsciiStr`
Migration (for details see new implementations):
- You can't construct `AsciiString` and `AsciiStr` like a collection
anymore, use the `from_bytes` or `from_str` method instead.
- `FromStr::from_str for AsciiString` and `AsciiStr::from_str` for
construction from string slices.
- To convert from the ascii types to bytes or strings please use the
new generic conversion traits `Into` and `AsRef` instead of `IntoString`, `IntoBytes` or …
=> Replace `Vec<Ascii>` and `[Ascii]` with newtypes

Cargo.toml, src/lib.rs
Also adds a direct usize index (since it's not variable-length encoded, there's no reason not to do this here).
I'd add that it's a bit confusing to me why we are declaring the Index traits for AsciiString at all; can't we just let Deref delegate everything?  I didn't change it because I suppose at this point it's backwards-incompatible to fix, but that seems like a cleaner design.
=> Add IndexMut traits.

src/ascii.rs
Some of the examples should probably just be tests.
=> Fix panics in Ascii's `.is_xxx()` methods and add examples.

src/ascii.rs
Allows static initialization, nicer pattern matches and comparisons.
Naming conventions:
* alphabetic: just use it. breaks CamelCase convention, but worth it for simplicity.
* digits: prepend _ to make them valid identifiers, but still short.
* non-alphanumeric but visible: Use Wikipedia names CamelCased, but remove -Mark endings.
* rarely used control codes: use uppercase acronym to deter use.
* more commonly used control codes: Expand and CamelCase acronym to preserve meaning, eg LineFeed not NewLine or LineBreak.
I'm not certain which control codes should be expanded; Currently BEL and DEL are, but should they?
I'm not sure whether this is a breaking change.
=>  Convert `Ascii` into an enum.

.travis.yml, src/ascii.rs, src/ascii_str.rs, src/ascii_string.rs, src/lib.rs
`AsciiCast` has un-rustic names, and doesn't work well for `Ascii` (see first commit)
Another issue is that the traits aren't implemented for their target type,which breaks the pattern `fn foo<B:Into<Bar>>(b: B)`.
Hopefully [`AsciiExt` gets stabilized](https://github.com/rust-lang/rust/issues/27809) soon.
(Then this could be used by `AsciiString.push()`)
`IntoAsciiStr` / The third commit is unfinished, just cherry-pick the first two if I don't finish it.
I haven't removed changed anything, so this is not a breaking change. The idea is to make a minor release, and then remove (Owned)AsciiCast, `Ascii::from_byte()` and more later.
=> Add traits IntoAscii* to replace (Owned)AsciiCast

Cargo.toml
He contributed significantly to the library, in particular the `no_std` feature and the conversion traits.
@tormol: Do you want to be listed in the authors list?
=> Add tormol to the list of authors

RELEASES.md, src/ascii_string.rs, src/lib.rs, tests.rs
`FromAsciiError` is designed to mimic `std::string::FromUtf8Error`.
This is a breaking change that should have been in my *breaking* pull request,
but was stashed away and forgotten.
=> error type for AsciiString

src/ascii_str.rs, src/lib.rs
This is basically the same as https://github.com/tomprogrammer/rust-ascii/pull/31, except with the `impl ExactSizeIterator for Lines` and associated tests removed. I'll add them in a future pr when I figure out how to implement them, but I don't think they're important enough to block everything else. I'll also modify the `Lines` iterator to use `memchr` in a future pr.
=> Iter focused

src/ascii_string.rs
This is implemented for std::String as well
=> Impl fmt::Write for AsciiString, and add tests

Cargo.toml, src/ascii_char.rs, src/ascii_string.rs, src/lib.rs
This commit implements the `Arbitrary` trait for the types `AsciiChar` and `AsciiString` as suggested in #35.
=> Implement `quickcheck::Arbitrary` support

src/ascii_string.rs, tests.rs
`String` implements `AsRef<[u8]>` as well.
=> implement AsRef<[u8]> for AsciiString

.travis.yml, README.md, src/ascii_char.rs, src/ascii_str.rs
`AsciiExt` is being deprecated in Rust 1.26 (which is about to become beta), and replaced by inherent methods.
This pull request follows Rusts footsteps by un-feature-gating the existing replacement methods and adding the remaining (except `is_ascii()`).
The next major release can then remove the `AsciiExt` impls completely.
While the purpose of this crate is to contain things removed from `std::ascii`, I don't see any use case of the trait as a generic bound. Adding a copy of it would count as a separate trait too.
(`Error::description()` is being soft-deprecated / hidden in Rust 1.27, but that method seems kind of useful in `#![no_std]` contexts where `format!()` doesn't work, so I kept the separate documentation and README mention.)
=> Follow Rusts deprecation of AsciiExt

RELEASES.md, src/ascii_str.rs, src/ascii_string.rs
Originally I wanted to preserve the trailing null byte in the conversions. However, for safety, I left it out in case we added methods later to convert a `&mut CStr` to a `&mut AsciiStr`, otherwise users could have changed the trailing null byte and invalidated safety guarantees. Then, for consistency, I changed the other methods to remove the trailing null byte.
=> Implement conversion methods on {CStr, CString}

.travis.yml, Cargo.toml, README.md, src/ascii_char.rs, src/ascii_str.rs, src/ascii_string.rs, src/free_functions.rs, src/lib.rs, src/serialization/ascii_char.rs, tests.rs
I said I'd finish up my changes this weekend, and here they are.
It naturally turned into much more work than expected, mostly because in the process i found unsound trait impls, many inconsistencies, a way to make a `const fn` for creating `AsciiChar` from `char`, and many other small things I felt like changing.
Changelog:
* Remove [unsound `impl From<&mut AsciiStr> for &mut [u8]` and for `&mut str`](https://github.com/tomprogrammer/rust-ascii/issues/64).
* Remove quickcheck.
* Rename `AsciiStr.trim_left()` and `AsciiStr.trim_right()` to `trim_start()` and `trim_end()`.
* Rename `AsciiChar::from{,_unchecked}()` to `from_ascii{,_unchecked}()`.
* Remove impls of deprecated `std::ascii::AsciiExt` trait.
* Rename some `AsciiChar` variants, most significantly `Null` to `Nul` (for consistency …
=> 1.0 changes

src/ascii_char.rs, src/ascii_str.rs, src/ascii_string.rs, src/free_functions.rs, src/lib.rs, tests.rs
This PR removes all `#![cfg_attr(rustfmt, rustfmt_skip)]` from files so that files are automatically formatted by IDEs and using `cargo fmt` when working on this crate.
It might also be worth considering adding a github CI action to make sure the crate is fully formatted, this can be done with `cargo fmt --verbose -- --check`.
The reason for this PR is to make it easier for people to contribute without worrying about formatting. Recently I created a local branch to make a PR, but since I use hard tabs, I had to reformat my code manually every few lines, which became annoying quickly.
I believe it is standard for rust projects to use `rustfmt` to format their code. This can also be customized with a `rustfmt.toml` file if you wish to enforce a specific format.
It is also possible to put a …
=> Removed `rustfmt_skip` guards from all files.

src/ascii_string.rs
Since 'Vec::new()' is already a const function,
there is no difference in generated MIR/ASM whether
`AsciiString::new()` is marked `const` or not.
I saw issue #56 is waiting to mark this function as 'const',
and this PR simply marks 'AsciiString::new()' as a const fn.
`cargo test` successfully passed all tests in my local environment.
Thank you for reviewing this PR :smile_cat: 
p.s.
I compared the generated MIR and ASM from https://play.rust-lang.org with/without `const`.
```rust
// Removing 'const' specifier does not change output of generated MIR & ASM :)
pub const fn new() -> Vec<i64> {
Vec::new()
}
/* ASM OUTPUT
playground::new:
movq	%rdi, %rax
movq	$8, (%rdi)
xorps	%xmm0, %xmm0
movups	%xmm0, 8(%rdi)
retq
*/
/* MIR OUTPUT
// WARNING: This output format is intended for human consumers …
```
=> Mark AsciiString::new() as 'const fn'

src/ascii_char.rs, src/ascii_str.rs, src/ascii_string.rs, src/lib.rs, tests.rs
This PR fixes some clippy lints existing in the crate and adds `#![warn(...)]`s for others.
Also I'm not sure this PR looks right in terms of commits and merges, I tried my best to be up to date with upstream/master, but I think I ended up doing worse. I'm not sure how to fix it, but if necessary, I'll try my best to make this look better.
This PR also depends on the PR I made earlier on `unsafe` for documentation, although I didn't mean for this, I'm just new to git and thought a new branch by default would go off master and not the current branch.
=> Fix clippy lints

src/ascii_char.rs, src/ascii_str.rs, src/ascii_string.rs, src/free_functions.rs, src/lib.rs
This PR documents all usages of `unsafe` within the crate. This was done to ensure no soundness holes exist and to document invariants of functions for when they may be worked in the future.
This PR depends on another PR I opened a bit ago, tomprogrammer/rust-ascii/pull/71, but if that pull is declined, I can attempt to undo those commits and salvage the new ones.
I should also note I'm relatively new to PRs, if opening this PR while the other one is still open cause issues, I'll attempt to fix them to the best of my abilities.
=> Document all `unsafe` usages.

Cargo.toml, README.md, src/ascii_str.rs, src/ascii_string.rs, src/lib.rs
Enables `AsciiString` in `#![no_std]`-mode by using the `alloc` crate instead of `std`.  
Methods using `CStr` or `CString`, and impls of `Error` still require `std`.
Is it worth adding a feature for this? (or should `AsciiString` be always available or still require `std` feature?)
=> Add alloc feature

src/ascii_string.rs
The Rust stdlib has implemented `From<char> for String`, so it makes sense to me that we should have the Ascii equivalent.
=> Add From<AsciiChar> for AsciiString

src/ascii_string.rs
At the moment, `AsciiString` has `push`, `insert`, and `push_str` methods, but no `insert_str`.
=> Add AsciiString::insert_str

src/ascii_char.rs, src/ascii_str.rs, src/ascii_string.rs, src/free_functions.rs, src/serialization/ascii_char.rs, src/serialization/ascii_str.rs, src/serialization/ascii_string.rs, tests.rs
Several of Clippy's newer lints are now failing against this codebase.
=> Fixed failing Clippy lints

.github/workflows/ci.yml, src/ascii_string.rs
The example creates a new `AsciiString::from_raw_parts` using a shared reference casted to a mutable pointer. This changes the example to use an exclusive reference/pointer.
=> Fix UB in documentation example

Cargo.toml, README.md, RELEASES.md, src/lib.rs
#89, #92 and #96 are not included: they will be released in a soon-ish 1.2.0
=> Release 1.1

.github/workflows/ci.yml, README.md, src/ascii_char.rs, src/ascii_str.rs, src/lib.rs
Existing methods made `const fn`:
* ~`AsciiStr::len()`~ (done in #95)
* ~`AsciiStr::is_empty()`~ (done in #95)
* `AsciiStr::as_str()`
* `AsciiStr::as_bytes()`
* `AsciiStr::trim()`
* `AsciiStr::trim_left()`
* `AsciiStr::trim_right()`
* `AsciiChar::from_ascii_unchecked()`
* `AsciiChar::as_printable_char()`
* ~`AsciiChar::is_digit()`~ (postponed)
New methods:
* `AsciiStr::new([AsciiChar])`
* `AsciiStr::from_ascii_bytes()`
* `AsciiStr::from_ascii_str()`
* `AsciiChar::try_new(char)`
Also switch back to `&&` and `||` in many methods, ~and `panic!()` in `AsciiChar::new()`~ (postponed).
This increases MSRV ~all the way to 1.57~ 1.56.
=> Use newer const fn features

src/ascii_char.rs, tests.rs
`SOX` is the wrong name. for this character.
Renaming the variant and adding `SOX` as associated constant
would break `use`s of it. both explicit and glob imports.
Fixes #78.
=> Replace `AsciiChar::SOX` with associated constant STX`

src/ascii_char.rs, src/ascii_string.rs
Rust 1.68.0 promoted the `bindings_with_variant_name` lint to "deny-by-default" :
https://github.com/rust-lang/rust/blob/1.68.0/RELEASES.md#compiler
Allowing this in a few places (i.e. adding `#[allow(bindings_with_variant_name)]` attributes in two doctest snippets) fixes the following compilation errors when running `cargo test` on Rust 1.68.0 or later:
```
---- src/ascii_char.rs - ascii_char::AsciiChar::from_ascii (line 297) stdout ----
error[E0170]: pattern binding `a` is named the same as one of the variants of the type `ascii::AsciiChar`
--> src/ascii_char.rs:299:5
|
5 | let a = AsciiChar::from_ascii('g').unwrap();
|     ^
|
= note: `#[deny(bindings_with_variant_name)]` on by default
error: aborting due to previous error
For more information about this error, try `rustc --explain …
```
=> allow "bindings_with_variant_name" lint where necessary (fixes compiling tests with Rust 1.68.0+)
